# Generated by Django 3.1.2 on 2020-11-12 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chupallaStore', '0002_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(),
        ),
    ]
